name: Mobile CI

on:
  pull_request:
    branches:
      - develop
    paths:
      - 'android/**'

defaults:
  run:
    working-directory: ./android

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setting up Java
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
      
      - name: Get gradle cache
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Grant execute permissions to gradle wrapper
        run: chmod +x ./gradlew

      - name: Create Google Services JSON File
        env:
          GOOGLE_SERVICES_JSON: ${{ secrets.GOOGLE_SERVICES_JSON }}
        run: echo $GOOGLE_SERVICES_JSON > ./app/google-services.json
      
      - name: Clean cache and build App
        run: ./gradlew clean build

      - name: Upload Lint report
        uses: actions/upload-artifact@v3
        with:
          name: lint_report
          path: /home/runner/work/prueba_mobile/prueba_mobile/android/app/build/reports/lint-results-debug.html

      - name: Test App
        run: ./gradlew test

      - name: Upload test report
        uses: actions/upload-artifact@v3
        with:
          name: unit_test_report
          path: app/build/reports/tests/testDebugUnitTest/

      - name: Instrumentation Test App
        run: |
          ./gradlew connectedAndroidTest || true

      - name: Upload instrumentation test report
        uses: actions/upload-artifact@v3
        with:
          name: instrumentation_test_report
          path: app/build/reports/androidTests/connected/debug/