name: Mobile CD

on:
  push:
    branches:
      - develop
    paths:
      - "android/**"

defaults:
  run:
    working-directory: ./android

jobs:
  deploy:
    name: Assemble and Upload to Firebase

    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setting up Java
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Get gradle cache
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle- 

      - name: Grant execute permissions to gradle wrapper
        run: chmod +x ./gradlew

      - name: Create Google Application Credentials JSON File
        env:
          GOOGLE_APPLICATION_CREDENTIALS: ${{secrets.GOOGLE_APPLICATION_CREDENTIALS}}
        run: |
          echo $GOOGLE_APPLICATION_CREDENTIALS > ./google-application-credentials.json
          ls -l
          echo ~
        # export GOOGLE_APPLICATION_CREDENTIALS="~/google-application-credentials.json"
      
      # - name: Build and deploy Debug
      #   run: ./gradlew assembleDebug appDistributionUploadDebug

      # - name: Build and deploy Debug
      #   env:
      #     GOOGLE_APPLICATION_CREDENTIALS: ${{secrets.GOOGLE_APPLICATION_CREDENTIALS}}
      #   run: ./gradlew assembleDebug appDistributionUploadDebug
